CREATE TABLE IF NOT EXISTS `RESERVATIONS` (
  `RESERVATION_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ROOM_TYPE` varchar(30) NOT NULL,
  `NO_OF_ADULTS` tinyint(4) NOT NULL,
  `NO_OF_CHILDREN` tinyint(4) NOT NULL,
  `CHECKIN_DATE` date NOT NULL,
  `CHECKOUT_DATE` date NOT NULL,
  `EMAIL` varchar(30) NOT NULL,
  `PHONE` varchar(20) NOT NULL,
  PRIMARY KEY (`RESERVATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
